// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import redis "github.com/moonactive/ma-redis-proxy/pkg/redis"

// RedisClient is an autogenerated mock type for the RedisClient type
type RedisClient struct {
	mock.Mock
}

// Execute provides a mock function with given fields: cmd
func (_m *RedisClient) Execute(cmd *redis.Command) ([]byte, error) {
	ret := _m.Called(cmd)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*redis.Command) []byte); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*redis.Command) error); ok {
		r1 = rf(cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
