name: Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Run tests
      run: |
        make test

  benchmark:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Run tests
        run: |
          make run MA_REDIS_PROXY_ADDR=tcp://127.0.0.1:7777 &> /dev/null &
          make redis-benchmark HOST=127.0.0.1 PORT=6379
          sleep 10
          make redis-benchmark HOST=127.0.0.1 PORT=7777
